name: flutter_firebase
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  intl: ^0.18.0
  cupertino_icons: ^1.0.8
  firebase_core: ^2.14.0
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.7.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
